In [14]:
import sys
import numpy as np

print('Python: {}'.format(sys.version))
print('Numpy: {}'.format(np.__version__))

Python: 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy: 1.16.2


In [15]:
# defining a scalar
x = 6 
x

6

In [16]:
# defining a vector
x = np.array((1,2,3))
x

array([1, 2, 3])

In [18]:
print("Vector dimensions: {}".format(x.shape))
print("Vector size: {}".format(x.size))

Vector dimensions: (3,)
Vector size: 3


In [20]:
#defining a matrix
x=np.matrix([[1,2,3], [4,5,6], [7,8,9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [21]:
print("Matrix dimensions: {}".format(x.shape))
print("Matrix size: {}".format(x.size))


Matrix dimensions: (3, 3)
Matrix size: 9


In [24]:
#define a matrix of a given dimension
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
print("Matrix dimensions: {}".format(x.shape))
print("Matrix size: {}".format(x.size))

Matrix dimensions: (5, 5)
Matrix size: 25


In [26]:
#define a matrix of a given dimension
x = np.ones((3,3,3))
x

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [27]:
print("Tensor dimensions: {}".format(x.shape))
print("Tensor size: {}".format(x.size))

Tensor dimensions: (3, 3, 3)
Tensor size: 27


In [28]:
#indexing
A = np.ones((5,5), dtype = np.int)
A

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
# indexing starts at 0
A[0,1] = 2
A

array([[1, 2, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
# assign all rows (:) of first column (0) to value 3
A[:,0] = 3
A

array([[3, 2, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1]])

In [32]:
A[:,:] = 5
A

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [33]:
# for higher dimensions, simply add an index
A = np.ones((5,5,5), dtype = np.int)
A [:, 0,0]=6
A

array([[[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [35]:
# matrix operations
A = np.matrix([[1,2], [3,4]])
B = np.ones((2,2), dtype = np.int)
A

matrix([[1, 2],
        [3, 4]])

In [37]:
B

array([[1, 1],
       [1, 1]])

In [38]:
#Addition
C = A + B
C

matrix([[2, 3],
        [4, 5]])

In [39]:
#Subtraction
D = A - B
D

matrix([[0, 1],
        [2, 3]])

In [40]:
#Multiplication
E = A * B
E 

matrix([[3, 3],
        [7, 7]])

In [41]:
#matrix transpose
A = np.array(range(9))
A = A.reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
B = A.T
B

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [43]:
C = B.T
C

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
A = np.array(range(10))
A = A.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
B = A.T
B

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [47]:
B.shape

(5, 2)

In [51]:
#tensors!
A = np.ones((3,3,3,3,3,3,3,3,3,3))
print(A.shape)
print(len(A.shape))
print(A.size)

(3, 3, 3, 3, 3, 3, 3, 3, 3, 3)
10
59049
